(deftheme rebecca-custom
  "Created 2020-07-10.")

(custom-theme-set-faces
 'rebecca-custom
 '(default ((t (:foreground "#f1eff8" :background "#292a44"))))
 '(cursor ((t (:background "#8eaee0"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#ccccff"))))
 '(highlight ((t (:background "#383a62" :foreground "#8eaee0"))))
 '(region ((t (:background "#663399"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:background "yellow")) (((class color) (min-colors 16) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 8)) (:foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(trailing-whitespace ((t (:background "#ff79c6"))))
 '(font-lock-builtin-face ((t (:foreground "#8eaee0"))))
 '(font-lock-comment-delimiter-face ((t (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#666699"))))
 '(font-lock-constant-face ((t (:foreground "#efe4a1"))))
 '(font-lock-doc-face ((t (:foreground "#666699"))))
 '(font-lock-function-name-face ((t (:weight bold :foreground "#2de0a7"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "#7aa5ff"))))
 '(font-lock-negation-char-face ((t (:foreground "#ff79c6"))))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#6dfedf"))))
 '(font-lock-type-face ((t (:foreground "#ae81ff"))))
 '(font-lock-variable-name-face ((t (:foreground "#a0a0c5"))))
 '(font-lock-warning-face ((t (:foreground "#ff79c6" :background "#383a62"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#efe4a1"))))
 '(link-visited ((t (:foreground "violet" :inherit (link)))))
 '(fringe ((t (:foreground "#a0a0c5" :background "#292a44"))))
 '(header-line ((t (:foreground "#ccccff"))))
 '(tooltip ((t (:foreground "#ccccff" :background "#383a62"))))
 '(mode-line ((t (:foreground "#ae81ff" :background "#663399"))))
 '(mode-line-active ((t (:inherit (mode-line)))))
 '(mode-line-buffer-id ((t (:foreground "#f1eff8"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box (:line-width 1 :color "#666699" :style nil) :foreground "#666699" :background "#292a44" :inherit (mode-line)))))
 '(isearch ((t (:weight bold :foreground "#ff79c6" :background "#383a62"))))
 '(isearch-fail ((t (:foreground "#383a62" :background "#ff79c6"))))
 '(lazy-highlight ((t (:foreground "#ccccff" :background "#383a62"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(git-gutter:modified ((t (:inherit default :foreground "royal blue" :weight bold))))
 '(whitespace-empty ((t (:background "#383a62" :foreground "firebrick"))))
 '(flycheck-error ((t (:background "maroon" :underline (:color "Red1" :style wave)))))
 '(smerge-base ((t (:background "#606000"))))
 '(flycheck-color-mode-line-error-face ((t (:background "#993333" :foreground "#ccccff"))))
 '(flycheck-color-mode-line-warning-face ((t (:background "#826831" :foreground "#ccccff"))))
 '(centaur-tabs-selected-modified ((t (:foreground "DarkOrange"))))
 '(centaur-tabs-unselected-modified ((t (:foreground "DarkOrange"))))
 )

(provide-theme 'rebecca-custom)
